# Generated by Django 4.2.28 on 2026-04-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('essay_snippet', models.TextField()),
                ('score', models.CharField(max_length=20)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ScoreHistory',
                'ordering': ['-scored_at'],
            },
        ),
    ]
